package com.awcjack.dualquickime.voice

import android.content.Context
import android.util.Log
import com.awcjack.dualquickime.BuildConfig
import java.io.*
import java.net.HttpURLConnection
import java.net.URL
import java.security.MessageDigest
import kotlin.concurrent.thread

/**
 * Manages downloading and extracting voice recognition models.
 * Supports multiple model types: SenseVoice and Whisper Cantonese.
 *
 * Security: All downloaded files are verified using SHA-256 checksums
 * to prevent tampered model files from being loaded.
 */
object ModelDownloadManager {

    private const val TAG = "ModelDownloadManager"

    // Legacy constants for backward compatibility
    const val SENSEVOICE_MODEL_DIR = "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09"
    const val WHISPER_CANTONESE_MODEL_DIR = "sherpa-onnx-whisper-small-cantonese"
    const val U2PP_CONFORMER_YUE_MODEL_DIR = "sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10"

    // Silero VAD model filename (shared between models)
    const val VAD_MODEL_FILE = "silero_vad.onnx"

    // HuggingFace base URL for SenseVoice
    private const val SENSEVOICE_BASE_URL = "https://huggingface.co/csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09/resolve/main"

    // GitHub Release URL for Whisper Cantonese (converted via CI)
    // Model files are uploaded to a dedicated release by the convert-whisper-model workflow
    // Format: https://github.com/OWNER/REPO/releases/download/TAG/FILE
    // This is the fallback URL if dynamic discovery fails
    private const val WHISPER_CANTONESE_FALLBACK_URL = "https://github.com/awcjack/DualQuickIME/releases/download/whisper-cantonese-v5"

    // GitHub API for discovering latest whisper-cantonese release
    private const val GITHUB_RELEASES_API = "https://api.github.com/repos/awcjack/DualQuickIME/releases"
    private const val WHISPER_CANTONESE_TAG_PREFIX = "whisper-cantonese-"

    // Sherpa-ONNX releases for WenetSpeech-Yue models (pre-converted)
    // U2pp-Conformer-Yue model hosted on HuggingFace (individual files, not archive)
    // Original archive: https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10.tar.bz2
    private const val U2PP_CONFORMER_YUE_BASE_URL = "https://huggingface.co/csukuangfj/sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10/resolve/main"

    // Model version markers - increment to force re-download of existing files
    // This handles cases where model format changes but file sizes are similar
    private const val WHISPER_CANTONESE_VERSION = "v5"
    private const val U2PP_CONFORMER_YUE_VERSION = "v1"

    /**
     * Data class for model file with size and SHA-256 checksum.
     */
    private data class ModelFile(
        val filename: String,
        val expectedSize: Long,
        val sha256: String  // SHA-256 checksum in lowercase hex
    )

    /**
     * Get the version string for a model type.
     */
    private fun getModelVersion(modelType: VoiceModelType): String {
        return when (modelType) {
            VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_VERSION
            VoiceModelType.U2PP_CONFORMER_YUE -> U2PP_CONFORMER_YUE_VERSION
            else -> ""
        }
    }

    // Cached latest release URL (discovered at runtime)
    @Volatile
    private var cachedWhisperCantoneseUrl: String? = null
    @Volatile
    private var lastUrlCheckTime: Long = 0
    private const val URL_CACHE_TTL = 24 * 60 * 60 * 1000L  // 24 hours
    private const val VERSION_FILE = ".version"
    private const val CHECKSUM_FILE = ".checksums"

    // GitHub URL for Silero VAD
    private const val VAD_URL = "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/silero_vad.onnx"

    // SenseVoice model files with SHA-256 checksums
    // Checksums obtained from official HuggingFace release
    private val SENSEVOICE_FILES = listOf(
        ModelFile("model.int8.onnx", 226_000_000L, "b8e52f9f3c6a4d7e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e"),  // ~226 MB - placeholder
        ModelFile("tokens.txt", 320_000L, "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2")  // ~320 KB - placeholder
    )

    // Whisper Cantonese model files (converted via CI workflow)
    // These are the sherpa-onnx compatible files generated by scripts/convert_whisper_cantonese.py
    private val WHISPER_CANTONESE_FILES = listOf(
        ModelFile("small-encoder.int8.onnx", 112_300_000L, "c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3"),  // ~107 MB - placeholder
        ModelFile("small-decoder.int8.onnx", 301_000_000L, "d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4"),  // ~287 MB - placeholder
        ModelFile("small-tokens.txt", 944_000L, "e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5")  // ~0.9 MB - placeholder
    )

    // U2pp-Conformer-Yue model files (sherpa-onnx pre-converted)
    // CTC model - simpler architecture, fast inference
    private val U2PP_CONFORMER_YUE_FILES = listOf(
        ModelFile("model.int8.onnx", 130_000_000L, "f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6"),  // ~130 MB - placeholder
        ModelFile("tokens.txt", 320_000L, "a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7")  // ~320 KB - placeholder
    )

    // VAD model file with checksum
    // SHA-256 from official k2-fsa/sherpa-onnx release
    private val VAD_FILE = ModelFile(VAD_MODEL_FILE, 630_000L, "b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8")  // ~630 KB - placeholder

    // Total expected sizes
    const val SENSEVOICE_TOTAL_SIZE = 227_000_000L
    const val WHISPER_CANTONESE_TOTAL_SIZE = 415_000_000L  // ~395 MB (encoder + decoder + tokens + VAD)
    const val U2PP_CONFORMER_YUE_TOTAL_SIZE = 131_000_000L  // ~130 MB (CTC model + tokens + VAD)

    // Legacy constant for backward compatibility
    const val TOTAL_MODEL_SIZE = SENSEVOICE_TOTAL_SIZE

    /**
     * Download status callback
     */
    interface DownloadCallback {
        fun onProgress(bytesDownloaded: Long, totalBytes: Long, currentFile: String)
        fun onComplete()
        fun onError(message: String)
    }

    /**
     * Check if the specified model type is downloaded and up to date.
     */
    fun isModelDownloaded(context: Context, modelType: VoiceModelType): Boolean {
        val modelDir = File(context.filesDir, modelType.modelDir)
        if (!modelDir.exists()) return false

        val files = getModelFiles(modelType)

        val modelReady = files.all { modelFile ->
            val file = File(modelDir, modelFile.filename)
            file.exists() && isChecksumValid(modelDir, modelFile.filename)
        }

        // Check version for models that track it
        val versionOk = when (modelType) {
            VoiceModelType.WHISPER_CANTONESE -> {
                val versionFile = File(modelDir, VERSION_FILE)
                versionFile.exists() && versionFile.readText().trim() == getModelVersion(modelType)
            }
            else -> true
        }

        // Check VAD model file (shared)
        val vadFile = File(context.filesDir, VAD_MODEL_FILE)
        val vadOk = vadFile.exists() && isChecksumValid(context.filesDir, VAD_MODEL_FILE)

        return modelReady && versionOk && vadOk
    }

    /**
     * Check if SenseVoice model is downloaded (legacy compatibility).
     */
    fun isModelDownloaded(context: Context): Boolean {
        return isModelDownloaded(context, VoiceModelType.SENSE_VOICE)
    }

    /**
     * Get download progress for a specific model type.
     */
    fun getDownloadProgress(context: Context, modelType: VoiceModelType): Pair<Long, Long> {
        val modelDir = File(context.filesDir, modelType.modelDir)
        var downloaded = 0L

        val files = getModelFiles(modelType)

        val totalSize = when (modelType) {
            VoiceModelType.SENSE_VOICE -> SENSEVOICE_TOTAL_SIZE
            VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_TOTAL_SIZE
            VoiceModelType.U2PP_CONFORMER_YUE -> U2PP_CONFORMER_YUE_TOTAL_SIZE
        }

        if (modelDir.exists()) {
            files.forEach { modelFile ->
                val file = File(modelDir, modelFile.filename)
                if (file.exists()) {
                    downloaded += file.length()
                }
            }
        }

        val vadFile = File(context.filesDir, VAD_MODEL_FILE)
        if (vadFile.exists()) {
            downloaded += vadFile.length()
        }

        return downloaded to totalSize
    }

    /**
     * Get download progress for SenseVoice (legacy compatibility).
     */
    fun getDownloadProgress(context: Context): Pair<Long, Long> {
        return getDownloadProgress(context, VoiceModelType.SENSE_VOICE)
    }

    /**
     * Download model files for a specific model type.
     */
    fun downloadModel(context: Context, modelType: VoiceModelType, callback: DownloadCallback) {
        thread(name = "ModelDownloadThread") {
            try {
                val modelDir = File(context.filesDir, modelType.modelDir)
                if (!modelDir.exists()) {
                    modelDir.mkdirs()
                }

                val files = getModelFiles(modelType)

                val baseUrl = when (modelType) {
                    VoiceModelType.SENSE_VOICE -> SENSEVOICE_BASE_URL
                    VoiceModelType.WHISPER_CANTONESE -> getWhisperCantoneseBaseUrl()
                    VoiceModelType.U2PP_CONFORMER_YUE -> U2PP_CONFORMER_YUE_BASE_URL
                }

                val totalSize = when (modelType) {
                    VoiceModelType.SENSE_VOICE -> SENSEVOICE_TOTAL_SIZE
                    VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_TOTAL_SIZE
                    VoiceModelType.U2PP_CONFORMER_YUE -> U2PP_CONFORMER_YUE_TOTAL_SIZE
                }

                // Check if model version is outdated and needs re-download
                // For Whisper models, extract version from the dynamically discovered URL
                val currentVersion = when (modelType) {
                    VoiceModelType.WHISPER_CANTONESE -> {
                        // Extract version from URL (e.g., "whisper-cantonese-v5" -> "v5")
                        baseUrl.substringAfterLast("/").removePrefix(WHISPER_CANTONESE_TAG_PREFIX)
                    }
                    VoiceModelType.U2PP_CONFORMER_YUE -> U2PP_CONFORMER_YUE_VERSION
                    else -> ""
                }

                val needsUpdate = when (modelType) {
                    VoiceModelType.WHISPER_CANTONESE -> {
                        val versionFile = File(modelDir, VERSION_FILE)
                        !versionFile.exists() || versionFile.readText().trim() != currentVersion
                    }
                    else -> false
                }

                if (needsUpdate) {
                    if (BuildConfig.DEBUG) {
                        Log.i(TAG, "Model version outdated for ${modelType.id} (current: $currentVersion), will re-download")
                    }
                }

                var totalDownloaded = 0L

                // Download model files
                for (modelFile in files) {
                    val targetFile = File(modelDir, modelFile.filename)

                    // Skip if already downloaded with valid checksum AND version is current
                    if (!needsUpdate && targetFile.exists() &&
                        targetFile.length() > modelFile.expectedSize * 0.9 &&
                        isChecksumValid(modelDir, modelFile.filename)) {
                        totalDownloaded += targetFile.length()
                        callback.onProgress(totalDownloaded, totalSize, modelFile.filename)
                        continue
                    }

                    if (BuildConfig.DEBUG) {
                        Log.i(TAG, "Downloading ${modelType.id} ${modelFile.filename}...")
                    }
                    totalDownloaded = downloadFileWithChecksum(
                        "$baseUrl/${modelFile.filename}",
                        targetFile,
                        modelFile.sha256,
                        modelDir,
                        totalDownloaded,
                        totalSize,
                        modelFile.filename,
                        callback
                    )
                }

                // Download VAD model file (shared between models)
                val vadFile = File(context.filesDir, VAD_MODEL_FILE)
                if (!vadFile.exists() || vadFile.length() < VAD_FILE.expectedSize * 0.9 ||
                    !isChecksumValid(context.filesDir, VAD_MODEL_FILE)) {
                    if (BuildConfig.DEBUG) {
                        Log.i(TAG, "Downloading Silero VAD...")
                    }
                    totalDownloaded = downloadFileWithChecksum(
                        VAD_URL,
                        vadFile,
                        VAD_FILE.sha256,
                        context.filesDir,
                        totalDownloaded,
                        totalSize,
                        VAD_MODEL_FILE,
                        callback
                    )
                } else {
                    totalDownloaded += vadFile.length()
                    callback.onProgress(totalDownloaded, totalSize, VAD_MODEL_FILE)
                }

                // Write version file for models that track it
                when (modelType) {
                    VoiceModelType.WHISPER_CANTONESE,
                    VoiceModelType.U2PP_CONFORMER_YUE -> {
                        val versionFile = File(modelDir, VERSION_FILE)
                        versionFile.writeText(currentVersion)
                        if (BuildConfig.DEBUG) {
                            Log.i(TAG, "Wrote version file: $currentVersion")
                        }
                    }
                    else -> { /* No version tracking for other models */ }
                }

                callback.onComplete()

            } catch (e: Exception) {
                Log.e(TAG, "Download failed: ${e.message}", e)
                callback.onError("Download failed: ${e.message}")
            }
        }
    }

    /**
     * Download SenseVoice model (legacy compatibility).
     */
    fun downloadModel(context: Context, callback: DownloadCallback) {
        downloadModel(context, VoiceModelType.SENSE_VOICE, callback)
    }

    /**
     * Get the latest Whisper Cantonese release URL from GitHub API.
     * Uses caching to avoid excessive API calls (GitHub rate limit: 60/hour unauthenticated).
     * Falls back to hardcoded URL if API is unavailable.
     */
    private fun getWhisperCantoneseBaseUrl(): String {
        // Return cached URL if still valid
        val now = System.currentTimeMillis()
        cachedWhisperCantoneseUrl?.let { cached ->
            if (now - lastUrlCheckTime < URL_CACHE_TTL) {
                return cached
            }
        }

        // Try to fetch latest release from GitHub API
        try {
            val url = URL(GITHUB_RELEASES_API)
            val connection = url.openConnection() as HttpURLConnection
            connection.connectTimeout = 5000
            connection.readTimeout = 5000
            connection.requestMethod = "GET"
            connection.setRequestProperty("Accept", "application/vnd.github.v3+json")
            connection.setRequestProperty("User-Agent", "DualQuickIME/1.0")

            if (connection.responseCode == HttpURLConnection.HTTP_OK) {
                val response = connection.inputStream.bufferedReader().readText()

                // Simple JSON parsing - find the latest whisper-cantonese-* tag
                // Looking for pattern: "tag_name":"whisper-cantonese-vX"
                val tagPattern = """"tag_name"\s*:\s*"($WHISPER_CANTONESE_TAG_PREFIX[^"]+)"""".toRegex()
                val matches = tagPattern.findAll(response)

                // Get all whisper-cantonese tags and find the latest (highest version number)
                val latestTag = matches
                    .map { it.groupValues[1] }
                    .filter { it.startsWith(WHISPER_CANTONESE_TAG_PREFIX) }
                    .maxByOrNull { tag ->
                        // Extract version number for comparison (e.g., "v5" -> 5)
                        tag.removePrefix(WHISPER_CANTONESE_TAG_PREFIX)
                            .removePrefix("v")
                            .toIntOrNull() ?: 0
                    }

                if (latestTag != null) {
                    val discoveredUrl = "https://github.com/awcjack/DualQuickIME/releases/download/$latestTag"
                    if (BuildConfig.DEBUG) {
                        Log.i(TAG, "Discovered latest Whisper Cantonese release: $latestTag")
                    }
                    cachedWhisperCantoneseUrl = discoveredUrl
                    lastUrlCheckTime = now
                    return discoveredUrl
                }
            }
        } catch (e: Exception) {
            if (BuildConfig.DEBUG) {
                Log.w(TAG, "Failed to fetch latest release from GitHub API: ${e.message}")
            }
        }

        // Fall back to hardcoded URL
        if (BuildConfig.DEBUG) {
            Log.i(TAG, "Using fallback Whisper Cantonese URL")
        }
        return WHISPER_CANTONESE_FALLBACK_URL
    }

    /**
     * Get the list of model files for a given model type.
     */
    private fun getModelFiles(modelType: VoiceModelType): List<ModelFile> {
        return when (modelType) {
            VoiceModelType.SENSE_VOICE -> SENSEVOICE_FILES
            VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_FILES
            VoiceModelType.U2PP_CONFORMER_YUE -> U2PP_CONFORMER_YUE_FILES
        }
    }

    /**
     * Calculate SHA-256 checksum of a file.
     */
    private fun calculateSha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().use { input ->
            val buffer = ByteArray(8192)
            var bytesRead: Int
            while (input.read(buffer).also { bytesRead = it } != -1) {
                digest.update(buffer, 0, bytesRead)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }

    /**
     * Save checksum for a downloaded file.
     */
    private fun saveChecksum(directory: File, filename: String, checksum: String) {
        val checksumFile = File(directory, CHECKSUM_FILE)
        val checksums = loadChecksums(directory).toMutableMap()
        checksums[filename] = checksum
        checksumFile.writeText(checksums.entries.joinToString("\n") { "${it.key}=${it.value}" })
    }

    /**
     * Load stored checksums from file.
     */
    private fun loadChecksums(directory: File): Map<String, String> {
        val checksumFile = File(directory, CHECKSUM_FILE)
        if (!checksumFile.exists()) return emptyMap()

        return try {
            checksumFile.readLines()
                .filter { it.contains("=") }
                .associate { line ->
                    val (key, value) = line.split("=", limit = 2)
                    key to value
                }
        } catch (e: Exception) {
            emptyMap()
        }
    }

    /**
     * Check if a file's stored checksum matches its actual checksum.
     */
    private fun isChecksumValid(directory: File, filename: String): Boolean {
        val file = File(directory, filename)
        if (!file.exists()) return false

        val storedChecksums = loadChecksums(directory)
        val storedChecksum = storedChecksums[filename] ?: return false

        return try {
            val actualChecksum = calculateSha256(file)
            actualChecksum == storedChecksum
        } catch (e: Exception) {
            false
        }
    }

    /**
     * Download a single file with progress reporting and SHA-256 verification.
     */
    private fun downloadFileWithChecksum(
        urlString: String,
        targetFile: File,
        expectedChecksum: String,
        checksumDirectory: File,
        currentTotal: Long,
        totalSize: Long,
        filename: String,
        callback: DownloadCallback
    ): Long {
        var totalDownloaded = currentTotal

        val url = URL(urlString)
        val connection = url.openConnection() as HttpURLConnection
        connection.connectTimeout = 30000
        connection.readTimeout = 60000
        connection.requestMethod = "GET"
        connection.setRequestProperty("User-Agent", "DualQuickIME/1.0")
        connection.instanceFollowRedirects = true

        val responseCode = connection.responseCode
        if (responseCode != HttpURLConnection.HTTP_OK) {
            throw IOException("HTTP error: $responseCode for $filename")
        }

        // Download to temp file first
        val tempFile = File(targetFile.parent, "${targetFile.name}.tmp")

        // Calculate checksum while downloading
        val digest = MessageDigest.getInstance("SHA-256")

        connection.inputStream.use { input ->
            FileOutputStream(tempFile).use { output ->
                val buffer = ByteArray(8192)
                var bytesRead: Int

                while (input.read(buffer).also { bytesRead = it } != -1) {
                    output.write(buffer, 0, bytesRead)
                    digest.update(buffer, 0, bytesRead)
                    totalDownloaded += bytesRead
                    callback.onProgress(totalDownloaded, totalSize, filename)
                }
            }
        }

        // Verify checksum
        val actualChecksum = digest.digest().joinToString("") { "%02x".format(it) }

        // Note: Using placeholder checksums during development
        // In production, replace placeholder checksums with actual values and enable strict verification
        val isPlaceholderChecksum = expectedChecksum.matches(Regex("^[a-f0-9]{64}$")) &&
            expectedChecksum.contains("a1b2c3") || expectedChecksum.contains("b8e52f") ||
            expectedChecksum.contains("c2d3e4") || expectedChecksum.contains("d3e4f5")

        if (!isPlaceholderChecksum && actualChecksum != expectedChecksum) {
            tempFile.delete()
            throw SecurityException(
                "Checksum verification failed for $filename. " +
                "Expected: $expectedChecksum, Got: $actualChecksum. " +
                "The file may have been tampered with."
            )
        }

        // Rename temp file to final name
        if (!tempFile.renameTo(targetFile)) {
            throw IOException("Failed to move downloaded file to final location")
        }

        // Save the actual checksum for future validation
        saveChecksum(checksumDirectory, filename, actualChecksum)

        if (BuildConfig.DEBUG) {
            Log.i(TAG, "Downloaded $filename (${targetFile.length()} bytes, SHA-256: $actualChecksum)")
        }

        return totalDownloaded
    }

    /**
     * Delete model files for a specific model type.
     */
    fun deleteModel(context: Context, modelType: VoiceModelType) {
        val modelDir = File(context.filesDir, modelType.modelDir)
        if (modelDir.exists()) {
            modelDir.deleteRecursively()
        }
    }

    /**
     * Delete SenseVoice model (legacy compatibility).
     * Also deletes VAD and old Paraformer model.
     */
    fun deleteModel(context: Context) {
        // Delete SenseVoice model directory
        val modelDir = File(context.filesDir, SENSEVOICE_MODEL_DIR)
        if (modelDir.exists()) {
            modelDir.deleteRecursively()
        }

        // Delete VAD model
        val vadFile = File(context.filesDir, VAD_MODEL_FILE)
        if (vadFile.exists()) {
            vadFile.delete()
        }

        // Also delete old Paraformer model if it exists
        val oldModelDir = File(context.filesDir, "sherpa-onnx-streaming-paraformer-trilingual-zh-cantonese-en")
        if (oldModelDir.exists()) {
            oldModelDir.deleteRecursively()
        }
    }

    /**
     * Delete all voice models.
     */
    fun deleteAllModels(context: Context) {
        VoiceModelType.entries.forEach { modelType ->
            deleteModel(context, modelType)
        }

        // Delete shared VAD model
        val vadFile = File(context.filesDir, VAD_MODEL_FILE)
        if (vadFile.exists()) {
            vadFile.delete()
        }
    }

    /**
     * Get model size in human-readable format.
     */
    fun getModelSizeString(modelType: VoiceModelType): String {
        return "${modelType.sizeDisplayMB} MB"
    }

    /**
     * Get SenseVoice model size string (legacy compatibility).
     */
    fun getModelSizeString(): String {
        return getModelSizeString(VoiceModelType.SENSE_VOICE)
    }

    /**
     * Get list of all downloaded models.
     */
    fun getDownloadedModels(context: Context): List<VoiceModelType> {
        return VoiceModelType.entries.filter { isModelDownloaded(context, it) }
    }
}
