package com.awcjack.dualquickime.voice

import android.content.Context
import android.util.Log
import java.io.*
import java.net.HttpURLConnection
import java.net.URL
import kotlin.concurrent.thread

/**
 * Manages downloading and extracting voice recognition models.
 * Supports multiple model types: SenseVoice and Whisper Cantonese.
 */
object ModelDownloadManager {

    private const val TAG = "ModelDownloadManager"

    // Legacy constants for backward compatibility
    const val SENSEVOICE_MODEL_DIR = "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09"
    const val WHISPER_CANTONESE_MODEL_DIR = "sherpa-onnx-whisper-small-cantonese"

    // Silero VAD model filename (shared between models)
    const val VAD_MODEL_FILE = "silero_vad.onnx"

    // HuggingFace base URL for SenseVoice
    private const val SENSEVOICE_BASE_URL = "https://huggingface.co/csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09/resolve/main"

    // GitHub Release URL for Whisper Cantonese (converted via CI)
    // Model files are uploaded to a dedicated release by the convert-whisper-model workflow
    // Format: https://github.com/OWNER/REPO/releases/download/TAG/FILE
    private const val WHISPER_CANTONESE_BASE_URL = "https://github.com/awcjack/DualQuickIME/releases/download/whisper-cantonese-v2"

    // GitHub URL for Silero VAD
    private const val VAD_URL = "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/silero_vad.onnx"

    // SenseVoice model files
    private val SENSEVOICE_FILES = listOf(
        "model.int8.onnx" to 226_000_000L,  // ~226 MB
        "tokens.txt" to 320_000L             // ~320 KB
    )

    // Whisper Cantonese model files (converted via CI workflow)
    // These are the sherpa-onnx compatible files generated by scripts/convert_whisper_cantonese.py
    private val WHISPER_CANTONESE_FILES = listOf(
        "small-encoder.int8.onnx" to 92_220_000L,    // ~88 MB
        "small-decoder.int8.onnx" to 194_540_000L,   // ~186 MB
        "small-tokens.txt" to 735_000L                // ~0.7 MB
    )

    // VAD model file
    private val VAD_FILE = VAD_MODEL_FILE to 630_000L  // ~630 KB

    // Total expected sizes
    const val SENSEVOICE_TOTAL_SIZE = 227_000_000L
    const val WHISPER_CANTONESE_TOTAL_SIZE = 288_000_000L  // ~274 MB (encoder + decoder + tokens)

    // Legacy constant for backward compatibility
    const val TOTAL_MODEL_SIZE = SENSEVOICE_TOTAL_SIZE

    /**
     * Download status callback
     */
    interface DownloadCallback {
        fun onProgress(bytesDownloaded: Long, totalBytes: Long, currentFile: String)
        fun onComplete()
        fun onError(message: String)
    }

    /**
     * Check if the specified model type is downloaded.
     */
    fun isModelDownloaded(context: Context, modelType: VoiceModelType): Boolean {
        val modelDir = File(context.filesDir, modelType.modelDir)
        if (!modelDir.exists()) return false

        val files = when (modelType) {
            VoiceModelType.SENSE_VOICE -> SENSEVOICE_FILES
            VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_FILES
        }

        val modelReady = files.all { (filename, _) ->
            File(modelDir, filename).exists()
        }

        // Check VAD model file (shared)
        val vadFile = File(context.filesDir, VAD_MODEL_FILE)

        return modelReady && vadFile.exists()
    }

    /**
     * Check if SenseVoice model is downloaded (legacy compatibility).
     */
    fun isModelDownloaded(context: Context): Boolean {
        return isModelDownloaded(context, VoiceModelType.SENSE_VOICE)
    }

    /**
     * Get download progress for a specific model type.
     */
    fun getDownloadProgress(context: Context, modelType: VoiceModelType): Pair<Long, Long> {
        val modelDir = File(context.filesDir, modelType.modelDir)
        var downloaded = 0L

        val files = when (modelType) {
            VoiceModelType.SENSE_VOICE -> SENSEVOICE_FILES
            VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_FILES
        }

        val totalSize = when (modelType) {
            VoiceModelType.SENSE_VOICE -> SENSEVOICE_TOTAL_SIZE
            VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_TOTAL_SIZE
        }

        if (modelDir.exists()) {
            files.forEach { (filename, _) ->
                val file = File(modelDir, filename)
                if (file.exists()) {
                    downloaded += file.length()
                }
            }
        }

        val vadFile = File(context.filesDir, VAD_MODEL_FILE)
        if (vadFile.exists()) {
            downloaded += vadFile.length()
        }

        return downloaded to totalSize
    }

    /**
     * Get download progress for SenseVoice (legacy compatibility).
     */
    fun getDownloadProgress(context: Context): Pair<Long, Long> {
        return getDownloadProgress(context, VoiceModelType.SENSE_VOICE)
    }

    /**
     * Download model files for a specific model type.
     */
    fun downloadModel(context: Context, modelType: VoiceModelType, callback: DownloadCallback) {
        thread(name = "ModelDownloadThread") {
            try {
                val modelDir = File(context.filesDir, modelType.modelDir)
                if (!modelDir.exists()) {
                    modelDir.mkdirs()
                }

                val files = when (modelType) {
                    VoiceModelType.SENSE_VOICE -> SENSEVOICE_FILES
                    VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_FILES
                }

                val baseUrl = when (modelType) {
                    VoiceModelType.SENSE_VOICE -> SENSEVOICE_BASE_URL
                    VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_BASE_URL
                }

                val totalSize = when (modelType) {
                    VoiceModelType.SENSE_VOICE -> SENSEVOICE_TOTAL_SIZE
                    VoiceModelType.WHISPER_CANTONESE -> WHISPER_CANTONESE_TOTAL_SIZE
                }

                var totalDownloaded = 0L

                // Download model files
                for ((filename, expectedSize) in files) {
                    val targetFile = File(modelDir, filename)

                    // Skip if already downloaded
                    if (targetFile.exists() && targetFile.length() > expectedSize * 0.9) {
                        totalDownloaded += targetFile.length()
                        callback.onProgress(totalDownloaded, totalSize, filename)
                        continue
                    }

                    Log.i(TAG, "Downloading ${modelType.id} $filename...")
                    totalDownloaded = downloadFile(
                        "$baseUrl/$filename",
                        targetFile,
                        totalDownloaded,
                        totalSize,
                        filename,
                        callback
                    )
                }

                // Download VAD model file (shared between models)
                val vadFile = File(context.filesDir, VAD_MODEL_FILE)
                if (!vadFile.exists() || vadFile.length() < VAD_FILE.second * 0.9) {
                    Log.i(TAG, "Downloading Silero VAD...")
                    totalDownloaded = downloadFile(
                        VAD_URL,
                        vadFile,
                        totalDownloaded,
                        totalSize,
                        VAD_MODEL_FILE,
                        callback
                    )
                } else {
                    totalDownloaded += vadFile.length()
                    callback.onProgress(totalDownloaded, totalSize, VAD_MODEL_FILE)
                }

                callback.onComplete()

            } catch (e: Exception) {
                Log.e(TAG, "Download failed: ${e.message}", e)
                callback.onError("Download failed: ${e.message}")
            }
        }
    }

    /**
     * Download SenseVoice model (legacy compatibility).
     */
    fun downloadModel(context: Context, callback: DownloadCallback) {
        downloadModel(context, VoiceModelType.SENSE_VOICE, callback)
    }

    /**
     * Download a single file with progress reporting.
     */
    private fun downloadFile(
        urlString: String,
        targetFile: File,
        currentTotal: Long,
        totalSize: Long,
        filename: String,
        callback: DownloadCallback
    ): Long {
        var totalDownloaded = currentTotal

        val url = URL(urlString)
        val connection = url.openConnection() as HttpURLConnection
        connection.connectTimeout = 30000
        connection.readTimeout = 60000
        connection.requestMethod = "GET"
        connection.setRequestProperty("User-Agent", "DualQuickIME/1.0")
        connection.instanceFollowRedirects = true

        val responseCode = connection.responseCode
        if (responseCode != HttpURLConnection.HTTP_OK) {
            throw IOException("HTTP error: $responseCode for $filename")
        }

        // Download to temp file first
        val tempFile = File(targetFile.parent, "${targetFile.name}.tmp")

        connection.inputStream.use { input ->
            FileOutputStream(tempFile).use { output ->
                val buffer = ByteArray(8192)
                var bytesRead: Int

                while (input.read(buffer).also { bytesRead = it } != -1) {
                    output.write(buffer, 0, bytesRead)
                    totalDownloaded += bytesRead
                    callback.onProgress(totalDownloaded, totalSize, filename)
                }
            }
        }

        // Rename temp file to final name
        tempFile.renameTo(targetFile)
        Log.i(TAG, "Downloaded $filename (${targetFile.length()} bytes)")

        return totalDownloaded
    }

    /**
     * Delete model files for a specific model type.
     */
    fun deleteModel(context: Context, modelType: VoiceModelType) {
        val modelDir = File(context.filesDir, modelType.modelDir)
        if (modelDir.exists()) {
            modelDir.deleteRecursively()
        }
    }

    /**
     * Delete SenseVoice model (legacy compatibility).
     * Also deletes VAD and old Paraformer model.
     */
    fun deleteModel(context: Context) {
        // Delete SenseVoice model directory
        val modelDir = File(context.filesDir, SENSEVOICE_MODEL_DIR)
        if (modelDir.exists()) {
            modelDir.deleteRecursively()
        }

        // Delete VAD model
        val vadFile = File(context.filesDir, VAD_MODEL_FILE)
        if (vadFile.exists()) {
            vadFile.delete()
        }

        // Also delete old Paraformer model if it exists
        val oldModelDir = File(context.filesDir, "sherpa-onnx-streaming-paraformer-trilingual-zh-cantonese-en")
        if (oldModelDir.exists()) {
            oldModelDir.deleteRecursively()
        }
    }

    /**
     * Delete all voice models.
     */
    fun deleteAllModels(context: Context) {
        VoiceModelType.entries.forEach { modelType ->
            deleteModel(context, modelType)
        }

        // Delete shared VAD model
        val vadFile = File(context.filesDir, VAD_MODEL_FILE)
        if (vadFile.exists()) {
            vadFile.delete()
        }
    }

    /**
     * Get model size in human-readable format.
     */
    fun getModelSizeString(modelType: VoiceModelType): String {
        return "${modelType.sizeDisplayMB} MB"
    }

    /**
     * Get SenseVoice model size string (legacy compatibility).
     */
    fun getModelSizeString(): String {
        return getModelSizeString(VoiceModelType.SENSE_VOICE)
    }

    /**
     * Get list of all downloaded models.
     */
    fun getDownloadedModels(context: Context): List<VoiceModelType> {
        return VoiceModelType.entries.filter { isModelDownloaded(context, it) }
    }
}
